### ISSUE TITLE
Windows Search

### ISSUE THREAD

**Issue by Gengarm** [gordonbay/Windows-On-Reins#8]
Windows search is disabled/doesnt work after the script is ran, any way to fix this?

**Comment by Gengarm** [comment]
Still nothing?

**Comment by gordonbay** [comment]
I think i fixed in the new update

**Comment by Gengarm** [comment]
Yep, works now. I have some other problems now though, Mullvad (The VPN) does not work anymore or is giving me DNS connection errors. Do you mabye know if any new updates in your program might have caused this or know of a way to revert some of the changes the script makes? I also cannot open the Windows Security/Firewall page anymore. Any help would be appreciated!!!

**Comment by Gengarm** [comment]
Nvm 
"Function EnableDnsCache {	
	RegChange "SYSTEM\CurrentControlSet\services\Dnscache" "Start" "2" "Enabling DNS Cache Service" "DWord"
}"
Makes it work again lol. Opening the Windows Security tabs is still an issue which I cant figure out on my own, would be an bigger issue if I wasnt using 3rd party software but yea.

**Comment by gordonbay** [comment]
No need to call EnableDnsCache manually. There is a config called $beVpnPppoeSafe, just set it to 1.
If you had run the script just once with $unnistallWindowsDefender set to 1, its gone. Irreversible right now.

**Comment by Gengarm** [comment]
Thanks for the tip. The Windows Defender thing kinda sucks but whatever, 3rd party software works better usually.
